name: Laravel

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_USER: sail
          MYSQL_PASSWORD: password
          MYSQL_DATABASE: laravel
          MYSQL_ROOT_PASSWORD: password
          DB_PORT: ${{ job.services.mysql.ports[3306] }}
        ports:
          - 33306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
      - uses: actions/checkout@v3
      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      - name: Generate key
        run: php artisan key:generate
      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache
      - name: Run PHP CS Fixer
        run: |
          composer global require friendsofphp/php-cs-fixer --no-progress --no-suggest
          php-cs-fixer fix --diff --dry-run --verbose
        env:
          PATH: ${{ runner.tool_cache }}/composer/vendor/bin:$PATH
      - name: Execute tests (Unit and Feature tests) via PHPUnit
        env:
          DB_CONNECTION: mysql
          DB_DATABASE: laravel
          DB_PORT: 33306
          DB_HOST: 127.0.0.1
          DB_USER: sail
          DB_PASSWORD: password
        run: |
          php artisan migrate
          php artisan test
